### ISSUE TITLE
Spurious errors due to Docker BuildKit

### ISSUE THREAD

**Issue by CraigFe** [ocurrent/ocaml-ci#93] opened 2020-01-21 14:21 UTC
A significant proportion of CI jobs fail with the following spurious error:

```
#5 [internal] load metadata for docker.io/ocurrent/opam@sha256:8115c13b8c30...
#5 DONE 0.0s

#10 [internal] load build context
#10 transferring context: 453.44kB 0.0s done
#10 DONE 0.1s
failed to solve with frontend dockerfile.v0: failed to solve with frontend gateway.v0: rpc error: code = Unknown desc = failed to build LLB: executor failed running [/bin/sh -c (opam install ocaml-ci-web ocaml-ci-service ocaml-ci-client ocaml-ci-api --dry-run --deps-only -ty; echo $? > /tmp/exit-status) | tee /tmp/opam-plan; exit $(cat /tmp/exit-status)]: runc did not terminate sucessfully
2020-01-20 13:04.46: Job failed: Docker build exited with status 1
2020-01-20 13:04.46: Log analysis:
2020-01-20 13:04.46: >>> #10 DONE 0.1s
failed to solve with frontend dockerfile.v0: failed to solve with frontend gateway.v0: rpc error: code = Unknown desc = failed to build LLB: executor failed running [/bin/sh -c (opam install ocaml-ci-web ocaml-ci-service ocaml-ci-client ocaml-ci-api --dry-run --deps-only -ty; echo $? > /tmp/exit-status) | tee /tmp/opam-plan; exit $(cat /tmp/exit-status)]: runc did not terminate sucessfully (score = 10)
2020-01-20 13:04.46: BuildKit missing output
```

It's not clear to me what's causing this; I know @talex5 has some ideas.

**Comment by talex5** [comment] 2020-01-21 14:31
I suspect it's a bug in Docker's BuildKit. Perhaps it forgets to flush the output before exiting on error? At least, it seems strange that we receive the `DONE` line and the `failed to solve` with nothing in between. We use `FD_copy Unix.stdout` as stderr, so I don't see how the problem could be at our end.

Might be worth trying to reproduce it without OCurrent. Would also be interesting to check whether this problem only occurs with remote Docker instances, or with local ones too.

**Comment by talex5** [comment] 2020-05-11 13:47
Duplicate of https://github.com/ocurrent/ocurrent/issues/140

**Closed** 2022-05-25 13:00 UTC
Labels: bug
