### ISSUE TITLE
Expose ignored projects in Web UI

### ISSUE THREAD

**Issue by tmcgilchrist** [ocurrent/ocaml-ci#424] opened 2022-02-17 22:51 UTC
We expect that users/orgs adding ocaml-ci will select specific projects to build, what often happens is someone installs the ocaml-ci GH app and enables build for all repositories. We warn about this situation in the logs and don't build everything. 

The experience would be better if we exposed the projects we have discarded and clearly noted why they are not building.

**Comment by MisterDA** [comment] 2022-05-13 13:08
Duplicate of your own #392 :computer: .

**Closed by MisterDA** 2022-05-13 13:08 UTC
Labels: enhancement, causing-pain
